export { default as Navbar } from "./navbar/navbar";
export { default as Carousel } from "./carousel/carousel";
export { default as WhyChoose } from "./whyChoose/whyChoose";
export { default as HowItWorks } from "./howItWorks/howItWorks";
export { default as OurProducts } from "./ourProducts/ourProducts";
export { default as BankingPartners } from "./bankingPartners/bankingPartners";
export { default as CustomerFeedback } from "./customerFeedback/customerFeedback";
export { default as DownloadApp } from "./downloadApp/downloadApp";
export { default as Footer } from "./footer/footer";
